export const categoriesData = [
    { key: "software_development", label: "Software Development" },
    { key: "frontend_development", label: "Frontend Development" },
    { key: "backend_development", label: "Backend Development" },
    { key: "fullstack_development", label: "Fullstack Development" },
    { key: "mobile_app_development", label: "Mobile App Development" },
    { key: "devops", label: "DevOps" },
    { key: "cloud_computing", label: "Cloud Computing" },
    { key: "data_science", label: "Data Science" },
    { key: "machine_learning", label: "Machine Learning" },
    { key: "cybersecurity", label: "Cybersecurity" },
    { key: "database_management", label: "Database Management" },
    { key: "software_testing", label: "Software Testing" },
    { key: "agile_methodology", label: "Agile Methodology" },
    { key: "system_design", label: "System Design" },
    { key: "project_management", label: "Project Management" },
    { key: "performance_optimization", label: "Performance Optimization" },
    { key: "ui_ux_design", label: "UI/UX Design" },
    { key: "containerization", label: "Containerization" },
    { key: "api_management", label: "API Management" },
    { key: "distributed_systems", label: "Distributed Systems" },
    { key: "security_practices", label: "Security Practices" },
    { key: "internet_of_things", label: "Internet of Things (IoT)" },
    { key: "blockchain", label: "Blockchain" }
];
