export const topicsData = [
    { key: "agile_methodology", label: "Agile Methodology" },
    { key: "devops", label: "DevOps" },
    { key: "software_architecture", label: "Software Architecture" },
    { key: "microservices", label: "Microservices" },
    { key: "continuous_integration", label: "Continuous Integration" },
    { key: "object_oriented_design", label: "Object-Oriented Design" },
    { key: "cloud_computing", label: "Cloud Computing" },
    { key: "test_driven_development", label: "Test-Driven Development" },
    { key: "version_control", label: "Version Control" },
    { key: "api_design", label: "API Design" },
    { key: "data_structures", label: "Data Structures" },
    { key: "algorithms", label: "Algorithms" },
    { key: "design_patterns", label: "Design Patterns" },
    { key: "distributed_systems", label: "Distributed Systems" },
    { key: "refactoring", label: "Refactoring" },
    { key: "performance_optimization", label: "Performance Optimization" },
    { key: "database_design", label: "Database Design" },
    { key: "containerization", label: "Containerization" },
    { key: "security_practices", label: "Security Practices" },
    { key: "frontend_development", label: "Frontend Development" },
    { key: "backend_development", label: "Backend Development" },
    { key: "fullstack_development", label: "Fullstack Development" },
    { key: "mobile_app_development", label: "Mobile App Development" },
    { key: "user_experience", label: "User Experience (UX) Design" }
];
